import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Send, Bot, User, PanelRightClose, PanelRightOpen } from "lucide-react";

interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
}

interface ChatPanelProps {
  selectedResponse?: { id: string; text: string };
}

export const ChatPanel = ({ selectedResponse }: ChatPanelProps) => {
  const [isCollapsed, setIsCollapsed] = useState(true);
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      role: "assistant",
      content: "Hello! I'm your AI assistant. Click on any response to understand why a particular theme was assigned, or ask me anything about the codeframe analysis.",
    },
  ]);
  const [input, setInput] = useState("");

  const handleSend = () => {
    if (!input.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input,
    };

    setMessages((prev) => [...prev, userMessage]);

    // Simulate AI response
    setTimeout(() => {
      const aiResponse: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: generateResponse(input, selectedResponse?.text),
      };
      setMessages((prev) => [...prev, aiResponse]);
    }, 800);

    setInput("");
  };

  const generateResponse = (question: string, context?: string) => {
    if (context) {
      return `Based on the response "${context}", the theme was assigned because the language patterns and sentiment indicators matched the trained classification model. The key phrases identified were relevant to the thematic structure we've established.`;
    }
    
    const responses = [
      "The codeframe was generated by analyzing response patterns, identifying recurring themes, and clustering similar sentiments together.",
      "I've processed all responses considering the question context and identified common themes that emerged naturally from the data.",
      "The themes are derived from semantic analysis where I evaluated word frequency, co-occurrence patterns, and contextual meaning.",
    ];
    
    return responses[Math.floor(Math.random() * responses.length)];
  };

  if (isCollapsed) {
    return (
      <div className="h-full flex flex-col items-center pt-4">
        <Button
          variant="outline"
          size="icon"
          onClick={() => setIsCollapsed(false)}
          className="h-10 w-10"
        >
          <PanelRightOpen className="h-5 w-5" />
        </Button>
        <span className="text-xs text-muted-foreground mt-2 writing-mode-vertical">AI Assistant</span>
      </div>
    );
  }

  return (
    <Card className="h-full flex flex-col border-border/50">
      <CardHeader className="border-b border-border/50 pb-4">
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <Bot className="h-5 w-5 text-primary" />
            AI Assistant
          </CardTitle>
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setIsCollapsed(true)}
            className="h-8 w-8"
          >
            <PanelRightClose className="h-4 w-4" />
          </Button>
        </div>
        {selectedResponse && (
          <p className="text-xs text-muted-foreground mt-2 line-clamp-2">
            Discussing: "{selectedResponse.text}"
          </p>
        )}
      </CardHeader>

      <CardContent className="flex-1 flex flex-col p-0">
        <ScrollArea className="flex-1 p-4">
          <div className="space-y-4">
            {messages.map((message) => (
              <div
                key={message.id}
                className={`flex gap-3 ${message.role === "user" ? "flex-row-reverse" : ""}`}
              >
                <div
                  className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${
                    message.role === "user"
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted"
                  }`}
                >
                  {message.role === "user" ? (
                    <User className="h-4 w-4" />
                  ) : (
                    <Bot className="h-4 w-4" />
                  )}
                </div>
                <div
                  className={`flex-1 rounded-lg p-3 ${
                    message.role === "user"
                      ? "bg-primary text-primary-foreground"
                      : "bg-muted"
                  }`}
                >
                  <p className="text-sm">{message.content}</p>
                </div>
              </div>
            ))}
          </div>
        </ScrollArea>

        <div className="border-t border-border/50 p-4">
          <div className="flex gap-2">
            <Input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSend()}
              placeholder="Ask about theme assignments..."
              className="flex-1"
            />
            <Button onClick={handleSend} size="icon">
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};