import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Send, Bot, User, PanelRightClose, PanelRightOpen, SlidersHorizontal } from "lucide-react";
interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
}
interface ChatPanelProps {
  selectedResponse?: {
    id: string;
    text: string;
  };
  selectedQuestion?: {
    text: string;
    themes: {
      name: string;
      description: string;
    }[];
  };
  isCollapsed: boolean;
  onToggleCollapse: () => void;
}
export const ChatPanel = ({
  selectedResponse,
  selectedQuestion,
  isCollapsed,
  onToggleCollapse
}: ChatPanelProps) => {
  const [messages, setMessages] = useState<Message[]>([{
    id: "1",
    role: "assistant",
    content: "Hello! I'm your AI assistant. Select a question to get context-aware insights, or click on any response to understand why a particular theme was assigned."
  }]);
  const [input, setInput] = useState("");
  const handleSend = () => {
    if (!input.trim()) return;
    const userMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input
    };
    setMessages(prev => [...prev, userMessage]);

    // Simulate AI response with question context
    setTimeout(() => {
      const aiResponse: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: generateResponse(input, selectedResponse?.text, selectedQuestion)
      };
      setMessages(prev => [...prev, aiResponse]);
    }, 800);
    setInput("");
  };
  const generateResponse = (userQuestion: string, responseContext?: string, questionContext?: {
    text: string;
    themes: {
      name: string;
      description: string;
    }[];
  }) => {
    const lowerQuestion = userQuestion.toLowerCase();

    // If discussing a specific response
    if (responseContext) {
      return `Based on the response "${responseContext}", I assigned this theme because the language patterns indicate clear sentiment alignment. The key phrases match our established thematic categories for ${questionContext?.text || "this question"}.`;
    }

    // Context-aware responses based on selected question
    if (questionContext) {
      const themeNames = questionContext.themes.map(t => t.name).join(", ");
      if (lowerQuestion.includes("theme") || lowerQuestion.includes("code")) {
        return `For the question "${questionContext.text}", I identified ${questionContext.themes.length} main themes: ${themeNames}. These themes emerged from analyzing recurring patterns in customer responses, grouping similar sentiments and topics together.`;
      }
      if (lowerQuestion.includes("why") || lowerQuestion.includes("how")) {
        return `The themes for "${questionContext.text}" were generated by analyzing semantic patterns. For example, responses mentioning ease of use, intuitive design, or simple navigation were grouped under usability-related themes. The AI looked for co-occurring keywords and sentiment indicators.`;
      }
      if (lowerQuestion.includes("summary") || lowerQuestion.includes("insight")) {
        return `Key insights from "${questionContext.text}": The most prominent theme is "${questionContext.themes[0]?.name || 'N/A'}" with responses showing strong sentiment patterns. Overall, customers express clear opinions about ${questionContext.themes[0]?.description?.toLowerCase() || 'various aspects of the product'}.`;
      }
      if (lowerQuestion.includes("sentiment") || lowerQuestion.includes("positive") || lowerQuestion.includes("negative")) {
        return `Analyzing sentiment for "${questionContext.text}": The responses show a mix of positive and negative sentiments across themes like ${themeNames}. Positive responses typically highlight ease of use and satisfaction, while negative ones focus on areas needing improvement.`;
      }

      // Default context-aware response
      return `Regarding "${questionContext.text}": I've identified ${questionContext.themes.length} themes (${themeNames}). Each theme groups responses with similar language patterns and sentiment. Would you like me to explain the reasoning behind any specific theme assignment?`;
    }

    // Fallback when no question is selected
    return "Please select a question from the dropdown to get context-aware insights. Once selected, I can help you understand the themes, sentiment patterns, and reasoning behind the codeframe assignments.";
  };
  if (isCollapsed) {
    return <div className="h-full flex flex-col items-center pt-4 border border-slate-200 rounded-lg bg-white shadow-sm">
        <Button variant="outline" size="icon" onClick={onToggleCollapse} className="h-10 w-10 border-slate-200">
          <PanelRightOpen className="h-5 w-5 text-slate-600" />
        </Button>
        <span className="text-xs text-slate-500 mt-2 [writing-mode:vertical-lr]">AI Assistant</span>
      </div>;
  }
  return <Card className="h-full flex flex-col border-slate-200 bg-white shadow-sm overflow-hidden">
      <div className="flex items-center justify-between px-4 py-3 bg-slate-800 shrink-0">
        <h2 className="text-sm font-medium text-white">Chat</h2>
        <div className="flex items-center gap-2">
          <SlidersHorizontal className="h-4 w-4 text-slate-400" />
          <Button variant="ghost" size="icon" onClick={onToggleCollapse} className="h-6 w-6 text-slate-400 hover:text-white hover:bg-slate-700">
            <PanelRightClose className="h-4 w-4" />
          </Button>
        </div>
      </div>
      

      <ScrollArea className="flex-1">
        <div className="p-4 space-y-4">
          {messages.map(message => <div key={message.id} className={`flex gap-3 ${message.role === "user" ? "flex-row-reverse" : ""}`}>
              <div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full ${message.role === "user" ? "bg-emerald-700 text-white" : "bg-slate-100"}`}>
                {message.role === "user" ? <User className="h-4 w-4" /> : <Bot className="h-4 w-4 text-slate-600" />}
              </div>
              <div className={`flex-1 rounded-lg p-3 ${message.role === "user" ? "bg-emerald-700 text-white" : "bg-slate-100 text-slate-700"}`}>
                <p className="text-sm">{message.content}</p>
              </div>
            </div>)}
        </div>
      </ScrollArea>

      <div className="border-t border-slate-200 p-4 shrink-0">
        <div className="flex gap-2">
          <Input value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => e.key === "Enter" && handleSend()} placeholder="Ask about theme assignments..." className="flex-1 border-slate-200" />
          <Button onClick={handleSend} size="icon" className="bg-emerald-700 hover:bg-emerald-800">
            <Send className="h-4 w-4" />
          </Button>
        </div>
      </div>
    </Card>;
};